services:
  schaad.zip:
    build: .
    container_name: schaad.zip
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - ${DOCKER_NETWORK}
    volumes:
      - /var/www/schaad.zip/analytics:/app/data # Consistent analytics
      - ./public:/app/public

networks:
  proxy-network:
    external: true